version: '3.8'

services:
  ros2_humble_dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: ros2_humble_dev_image
    container_name: ros2_humble_container
    # ttyとstdin_openをtrueにして、コンテナを起動し続けて対話的に使えるようにする
    tty: true
    stdin_open: true
    # ボリュームマウント
    volumes:
      # ホストのsrcディレクトリをコンテナのワークスペースのsrcにマウント
      - ./src:/home/dockeruser/ros2_ws/src
      # X11 Forwarding (GUI表示) の設定
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # 環境変数
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    # ホストのネットワークをそのまま使う設定。ROSの通信が楽になる。
    network_mode: host
    # GPUを使いたい場合は下のコメントを外す
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]